version: "3"

mysqldb:
  image: mysql:8
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=sa
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=test

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  provider-jdbc:
    image: provider_image
    ports:
      - 8090:8090
#    networks:
#      - employee-mysql
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/test
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=root
    links:
      - kafka:kafka
      - mysqldb:mysql


