server:
  port: 8090
app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/test
    username: sa
    password: password
    pool-size: 30
spring:
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level: INFO

flyway:
enabled: true
schemas: EmployeeHistory
locations: classpath:/src/main/resources/db/migration

spring.flyway.baseline-on-migrate: true